"""
Constants and configurations for FocusLens.
"""

# Study States
STUDY_STATE_IDLE = "Idle"
STUDY_STATE_FOCUSED = "Focused"
STUDY_STATE_DISTRACTED = "Distracted"
STUDY_STATE_BREAK = "Break"
STUDY_STATE_FATIGUED = "Fatigued"

# Events
EVENT_SESSION_START = "SESSION_START"
EVENT_SESSION_END = "SESSION_END"
EVENT_SESSION_PAUSE = "SESSION_PAUSE"
EVENT_SESSION_RESUME = "SESSION_RESUME"
EVENT_FOCUS = "FOCUS"
EVENT_DISTRACTION = "DISTRACTION"
EVENT_PHONE_DETECTED = "PHONE_DETECTED"
EVENT_BREAK_START = "BREAK_START"
EVENT_BREAK_END = "BREAK_END"
EVENT_FATIGUE_DETECTED = "FATIGUE_DETECTED"

# Detected Objects
OBJECT_PERSON = "person"
OBJECT_PHONE = "phone"
OBJECT_BOOK = "book"
OBJECT_NOTEBOOK = "notebook"
OBJECT_COFFEE_CUP = "coffee_cup"
OBJECT_BACKPACK = "backpack"
OBJECT_KEYBOARD = "keyboard"
OBJECT_MOUSE = "mouse"
OBJECT_EMPTY_CHAIR = "empty_chair"

DETECTABLE_OBJECTS = [
    OBJECT_PERSON,
    OBJECT_PHONE,
    OBJECT_BOOK,
    OBJECT_NOTEBOOK,
    OBJECT_COFFEE_CUP,
    OBJECT_BACKPACK,
    OBJECT_KEYBOARD,
    OBJECT_MOUSE,
    OBJECT_EMPTY_CHAIR,
]

# Focus Levels
FOCUS_LEVEL_LOW = "Low"
FOCUS_LEVEL_MEDIUM = "Medium"
FOCUS_LEVEL_HIGH = "High"

# Thresholds
FOCUS_SCORE_HIGH = 80
FOCUS_SCORE_MEDIUM = 50
FOCUS_SCORE_LOW = 0

BREAK_RECOMMENDATION_THRESHOLD = 40  # minutes
FATIGUE_THRESHOLD = 70  # session minutes

# Time Settings (in seconds)
FRAME_INTERVAL = 5  # Capture every 5 seconds
COOLDOWN_VOICE_MESSAGE = 30  # Prevent repeating messages within 30 seconds
COOLDOWN_DISTRACTION = 60  # Don't report same distraction within 60 seconds

# Default Database Path
DEFAULT_DB_PATH = "focuslens.db"

# Speech
DEFAULT_VOICE_SPEED = 150
DEFAULT_VOICE_RATE = 1.0

# Gemini Model
GEMINI_MODEL = "gemini-2.5-flash"

# Colors for UI
COLOR_FOCUSED = "#4CAF50"
COLOR_DISTRACTED = "#FF9800"
COLOR_BREAK = "#2196F3"
COLOR_FATIGUED = "#F44336"
COLOR_IDLE = "#9E9E9E"

# Report Types
REPORT_TYPE_DAILY = "daily"
REPORT_TYPE_WEEKLY = "weekly"
REPORT_TYPE_CUSTOM = "custom"
